import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./components/LoginBtn/LoginBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SEOJIN PROJECT",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {


  return (
    <html lang="ko">
      <body>
        <div className="bg-1280px">
          <div className="nav">
            <Link href={'/'} className="logo logo-font">CatD</Link>
            <div className='nav-info'>
              <div className='user-about'>
                <LoginBtn/>
              </div>
              <div className="nav-list">
                <Link href={'/'}>Home</Link>
                <Link href={'/dic'}>Dictionary</Link>
                <Link href={'/'}>Supplies</Link>
                <Link href={'/community'}>Community</Link>
              </div>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
